(()=>{
'use strict';
const C=document.getElementById('gameCanvas'),X=C.getContext('2d'),COLS=16,ROWS=11,SAVE='empire-frontiers-save-v2',$=id=>document.getElementById(id);
const F=[
 {name:'Azure Crown',short:'AZURE',color:'#3dd5f3',dark:'#075e78'},
 {name:'Ember Dominion',short:'EMBER',color:'#ff685e',dark:'#842b28'},
 {name:'Verdant Pact',short:'VERDANT',color:'#72d378',dark:'#2e6836'},
 {name:'Violet Order',short:'VIOLET',color:'#bd82f4',dark:'#61368a'}];
const T={
 infantry:{name:'Infantry',mark:'INF',icon:'⚔',hp:13,atk:5,def:3,move:2,range:1,cost:{gold:7,food:5,wood:0},strong:['archer'],weak:['swordsman']},
 swordsman:{name:'Swordsman',mark:'SWD',icon:'🗡',hp:15,atk:7,def:4,move:2,range:1,cost:{gold:13,food:6,wood:2},strong:['infantry','archer','spear'],weak:['cavalry']},
 archer:{name:'Archer',mark:'ARC',icon:'🏹',hp:9,atk:5,def:2,move:2,range:3,cost:{gold:9,food:3,wood:5},strong:['spear'],weak:['infantry','swordsman','cavalry']},
 cavalry:{name:'Cavalry',mark:'CAV',icon:'♞',hp:14,atk:7,def:4,move:3,range:1,cost:{gold:14,food:7,wood:0},strong:['swordsman','archer'],weak:['spear']},
 spear:{name:'Spearmen',mark:'SPR',icon:'🔱',hp:14,atk:5,def:5,move:2,range:1,cost:{gold:8,food:5,wood:4},strong:['cavalry'],weak:['swordsman','archer']}
};
const N=['Dawnkeep','Ironvale','Riverwatch','Stonegate','Sunspire','Mossford','Starfall','Highmere'];
let S=null,sel=null,moves=[],targets=[],tw=50,th=50,ox=0,oy=0,timer;
const rnd=n=>Math.floor(Math.random()*n),K=(x,y)=>x+','+y,D=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
function terrain(x,y){const n=Math.sin(x*12.9898+y*78.233)*43758.5453%1;return Math.abs(n)<.12?'water':Math.abs(n)<.25?'forest':Math.abs(n)<.34?'hill':'plains'}
function mapData(){const map=[];for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++)map.push({x,y,terrain:terrain(x,y),resource:null,resourceLevel:1,owner:null});const pos=[[2,2],[13,8],[13,2],[2,8],[7,2],[8,8],[4,5],[11,5]];pos.forEach(([x,y])=>map[y*COLS+x].terrain='plains');for(let i=0;i<22;i++){const t=map[rnd(map.length)];if(t.terrain!=='water'&&!pos.some(p=>p[0]===t.x&&p[1]===t.y))t.resource=['gold','food','wood'][rnd(3)]}return{map,pos}}
function fresh(d='normal'){const{map,pos}=mapData(),cities=pos.map((p,i)=>({id:i,x:p[0],y:p[1],name:N[i],owner:i<4?i:null,capital:i<4,level:1})),units=[];for(let i=0;i<4;i++){const c=cities[i];units.push({id:crypto.randomUUID(),x:c.x,y:c.y,type:'infantry',owner:i,hp:13,rank:1,acted:false})}const s={version:3,turn:1,current:0,difficulty:d,map,cities,units,resources:F.map(()=>({gold:22,food:16,wood:12})),upgrades:F.map(()=>({arms:0,armor:0})),alive:[true,true,true,true]};territory(s);return s}
function migrate(s){s.version=3;s.upgrades||=F.map(()=>({arms:0,armor:0}));while(s.upgrades.length<4)s.upgrades.push({arms:0,armor:0});s.map.forEach(t=>t.resourceLevel||=1);s.cities.forEach(c=>c.level||=1);s.units.forEach(u=>u.rank||=1);territory(s);return s}
const tile=(x,y)=>x>=0&&y>=0&&x<COLS&&y<ROWS?S.map[y*COLS+x]:null,city=(x,y)=>S.cities.find(c=>c.x===x&&c.y===y),unit=(x,y)=>S.units.find(u=>u.x===x&&u.y===y);
const mh=u=>T[u.type].hp+(u.rank-1)*2+S.upgrades[u.owner].armor,atk=u=>T[u.type].atk+(u.rank-1)*2+S.upgrades[u.owner].arms,def=u=>T[u.type].def+(u.rank-1)+S.upgrades[u.owner].armor,power=u=>atk(u)+def(u)+Math.ceil(u.hp/3);
function territory(s=S){s.map.forEach(t=>t.owner=null);s.cities.forEach(c=>{if(c.owner==null)return;const r=2+Math.floor((c.level-1)/2);s.map.forEach(t=>{if(D(c,t)<=r&&t.terrain!=='water'&&t.owner==null)t.owner=c.owner})})}
function income(o){const out={gold:2,food:2,wood:2};S.cities.filter(c=>c.owner===o).forEach(c=>{out.gold+=1+c.level;out.food+=1+c.level;out.wood+=c.level});S.map.filter(t=>t.owner===o&&t.resource).forEach(t=>out[t.resource]+=3*t.resourceLevel);return out}
const afford=(o,c)=>Object.keys(c).every(k=>S.resources[o][k]>=c[k]),pay=(o,c)=>Object.keys(c).forEach(k=>S.resources[o][k]-=c[k]),cost=c=>`${c.gold||0}● ${c.food||0}◆ ${c.wood||0}▲`;
function reach(u){const seen=new Map([[K(u.x,u.y),0]]),q=[{x:u.x,y:u.y,d:0}],out=[];while(q.length){const p=q.shift();[[1,0],[-1,0],[0,1],[0,-1]].forEach(([dx,dy])=>{const x=p.x+dx,y=p.y+dy,t=tile(x,y);if(!t||t.terrain==='water')return;const d=p.d+(['forest','hill'].includes(t.terrain)?2:1);if(d>T[u.type].move||seen.has(K(x,y)))return;seen.set(K(x,y),d);const v=unit(x,y);if(!v||v.owner!==u.owner){out.push({x,y,enemy:!!v});if(!v)q.push({x,y,d})}else if(x!==u.x||y!==u.y)q.push({x,y,d})})}return out}
const inRange=u=>u.acted?[]:S.units.filter(v=>v.owner!==u.owner&&D(u,v)<=T[u.type].range).map(v=>({x:v.x,y:v.y}));
function select(x,y){if(S.current!==0)return;if(sel?.kind==='unit'&&targets.some(p=>p.x===x&&p.y===y))return fight(sel.data,unit(x,y),true);if(sel?.kind==='unit'&&moves.some(p=>p.x===x&&p.y===y))return move(sel.data,x,y);const u=unit(x,y),c=city(x,y),t=tile(x,y);if(u){sel={kind:'unit',data:u};moves=u.owner===0&&!u.acted?reach(u):[];targets=u.owner===0?inRange(u):[]}else if(c){sel={kind:'city',data:c};moves=[];targets=[]}else if(t?.resource){sel={kind:'resource',data:t};moves=[];targets=[]}else if(t?.owner===0&&t.terrain!=='water'){sel={kind:'land',data:t};moves=[];targets=[]}else{sel=null;moves=[];targets=[]}ui();draw()}
function modifier(a,d){return T[a.type].strong.includes(d.type)?1.55:(T[a.type].weak.includes(d.type)||T[d.type].strong.includes(a.type)?.72:1)}
function fight(a,d,ranged=false){if(!a||!d)return;const distance=D(a,d),m=modifier(a,d),cover=['forest','hill'].includes(tile(d.x,d.y).terrain)?1:0;const hit=Math.max(1,Math.round((atk(a)*m-(def(d)+cover)*.42)*(.68+.32*a.hp/mh(a))+Math.random()*2-.5));d.hp-=hit;a.acted=true;toast(`${T[a.type].name} dealt ${hit} damage${m>1?' — advantage!':m<1?' — resisted':''}`);if(d.hp<=0)S.units.splice(S.units.indexOf(d),1);else if(!(ranged&&distance>1)){const reply=Math.max(1,Math.round((atk(d)*modifier(d,a)-def(a)*.45)*.55));a.hp-=reply;if(a.hp<=0)S.units.splice(S.units.indexOf(a),1)}if(ranged){sel=S.units.includes(a)?{kind:'unit',data:a}:null;moves=[];targets=[];finish()}}
function move(u,x,y){const v=unit(x,y);if(v&&v.owner!==u.owner){fight(u,v,false);if(S.units.includes(u)&&!S.units.includes(v)){u.x=x;u.y=y;capture(u)}}else{u.x=x;u.y=y;u.acted=true;capture(u)}sel=S.units.includes(u)?{kind:'unit',data:u}:null;moves=[];targets=[];finish()}
function capture(u){const c=city(u.x,u.y);if(!c||c.owner===u.owner)return;const old=c.owner;c.owner=u.owner;c.level=Math.max(1,c.level-1);toast(`${F[u.owner].name} captured ${c.name}!`);territory();if(old!=null&&!S.cities.some(z=>z.owner===old))S.alive[old]=false;result()}
function heal(u){const miss=mh(u)-u.hp,c={gold:Math.max(2,Math.ceil(miss/3)),food:Math.max(2,Math.ceil(miss/2)),wood:0};if(!miss)return toast('This unit is already at full health.');if(tile(u.x,u.y).owner!==0)return toast('Heal units inside friendly territory.');if(!afford(0,c))return toast('Not enough resources to heal.');pay(0,c);u.hp=mh(u);u.acted=true;toast(`${T[u.type].name} restored to full health.`);finish()}
function rank(u){if(u.rank>=3)return toast('This unit is already elite.');const c={gold:7*u.rank,food:3*u.rank,wood:4*u.rank};if(!afford(0,c))return toast('Not enough resources to upgrade.');pay(0,c);u.rank++;u.hp=Math.min(mh(u),u.hp+4);u.acted=true;toast(`${T[u.type].name} promoted to rank ${u.rank}.`);finish()}
function improve(t){if(t.owner!==0)return toast('This resource is outside your territory.');if(t.resourceLevel>=3)return toast('This resource is fully developed.');const c={gold:6*t.resourceLevel,food:t.resource==='food'?2:0,wood:5*t.resourceLevel};if(!afford(0,c))return toast('Not enough resources.');pay(0,c);t.resourceLevel++;toast(`Production increased to level ${t.resourceLevel}.`);finish()}
function buildSite(t,type){if(t.owner!==0||t.resource)return;const costs={gold:{gold:0,food:7,wood:9},food:{gold:8,food:0,wood:7},wood:{gold:8,food:7,wood:0}},c=costs[type];if(!afford(0,c))return toast('Not enough resources to build this site.');pay(0,c);t.resource=type;t.resourceLevel=1;sel={kind:'resource',data:t};toast(`${type==='gold'?'Gold mine':type==='food'?'Farm':'Lumber camp'} built. +3 per turn.`);finish()}
function convertSite(t,type){if(t.owner!==0||t.resource===type)return;const c={gold:6,food:4,wood:4};if(!afford(0,c))return toast('Not enough resources to convert this site.');pay(0,c);t.resource=type;t.resourceLevel=1;toast(`Site converted to ${type==='gold'?'gold production':type==='food'?'food production':'wood production'}.`);finish()}
function develop(c){if(c.owner!==0||c.level>=3)return;const p={gold:12*c.level,food:7*c.level,wood:9*c.level};if(!afford(0,p))return toast('Not enough resources.');pay(0,p);c.level++;territory();toast(`${c.name} advanced to level ${c.level}.`);finish()}
function empire(kind,c){if(c.owner!==0)return;const l=S.upgrades[0][kind];if(l>=3)return toast('Upgrade complete.');const p={gold:14+l*10,food:kind==='armor'?5+l*3:0,wood:10+l*6};if(!afford(0,p))return toast('Not enough resources.');pay(0,p);S.upgrades[0][kind]++;if(kind==='armor')S.units.filter(u=>u.owner===0).forEach(u=>u.hp++);toast(kind==='arms'?'Every unit gained attack power.':'Every unit gained defense and health.');finish()}
function recruit(type,c){const t=T[type];if(c.owner!==0||unit(c.x,c.y))return toast('The city center must be clear.');if(!afford(0,t.cost))return toast('Not enough resources.');pay(0,t.cost);S.units.push({id:crypto.randomUUID(),x:c.x,y:c.y,type,owner:0,hp:t.hp+S.upgrades[0].armor,rank:1,acted:true});toast(`${t.name} recruited in ${c.name}.`);finish()}
function finish(){territory();save();ui();draw();result()}
function end(){if(S.current!==0)return;sel=null;moves=[];targets=[];ai(1)}
function ai(o){if(o>3)return playerTurn();if(!S.alive[o])return ai(o+1);S.current=o;$('phaseLabel').textContent=F[o].name+' moves';ui();setTimeout(()=>{const inc=income(o);Object.keys(inc).forEach(k=>S.resources[o][k]+=inc[k]);aiRecruit(o);[...S.units.filter(u=>u.owner===o)].forEach(aiMove);territory();draw();result();setTimeout(()=>ai(o+1),320)},380)}
function aiRecruit(o){const pool=S.difficulty==='hard'?['swordsman','cavalry','archer','spear','infantry']:['infantry','spear','archer','swordsman'];S.cities.filter(c=>c.owner===o&&!unit(c.x,c.y)).slice(0,S.difficulty==='easy'?1:2).forEach(c=>{const type=pool.find(t=>afford(o,T[t].cost));if(type){pay(o,T[type].cost);S.units.push({id:crypto.randomUUID(),x:c.x,y:c.y,type,owner:o,hp:T[type].hp+S.upgrades[o].armor,rank:1,acted:true})}})}
function aiMove(u){if(!S.units.includes(u))return;const shot=S.units.filter(v=>v.owner!==u.owner&&D(u,v)<=T[u.type].range).sort((a,b)=>a.hp-b.hp)[0];if(shot)return fight(u,shot,T[u.type].range>1);const cs=S.cities.filter(c=>c.owner!==u.owner).sort((a,b)=>D(u,a)-D(u,b));if(!cs.length)return;const m=reach(u).sort((a,b)=>D(a,cs[0])-D(b,cs[0]))[0];if(!m)return;const v=unit(m.x,m.y);if(v){fight(u,v,false);if(S.units.includes(u)&&!S.units.includes(v)){u.x=m.x;u.y=m.y;capture(u)}}else{u.x=m.x;u.y=m.y;u.acted=true;capture(u)}}
function playerTurn(){S.turn++;S.current=0;const inc=income(0);Object.keys(inc).forEach(k=>S.resources[0][k]+=inc[k]);S.units.filter(u=>u.owner===0).forEach(u=>{u.acted=false;if(tile(u.x,u.y).owner===0)u.hp=Math.min(mh(u),u.hp+1)});$('phaseLabel').textContent='Your command';toast(`Turn ${S.turn}: +${inc.gold} gold, +${inc.food} food, +${inc.wood} wood`);finish()}
function result(){const ours=S.cities.filter(c=>c.owner===0).length,rivals=S.cities.filter(c=>c.owner!=null&&c.owner!==0).length;if(rivals&&ours)return false;const win=!rivals;$('resultIcon').textContent=win?'♜':'⚑';$('resultKicker').textContent=win?'REALM UNITED':'THE CROWN HAS FALLEN';$('resultTitle').textContent=win?'Victory':'Defeat';$('resultText').textContent=win?`You united all eight cities in ${S.turn} turns.`:'Your last city was captured. Adjust your army mix and try again.';$('resultOverlay').classList.add('open');localStorage.removeItem(SAVE);return true}
function save(){localStorage.setItem(SAVE,JSON.stringify(S));$('continueGame').classList.remove('hidden')}
function button(label,detail,fn,disabled=false,cls=''){const b=document.createElement('button');b.className='action '+cls;b.disabled=disabled;b.innerHTML=`${label}<small>${detail}</small>`;b.onclick=fn;$('actions').appendChild(b)}
function ui(){const r=S.resources[0],inc=income(0);$('gold').textContent=r.gold;$('food').textContent=r.food;$('wood').textContent=r.wood;$('goldIncome').textContent='+'+inc.gold+'/turn';$('foodIncome').textContent='+'+inc.food+'/turn';$('woodIncome').textContent='+'+inc.wood+'/turn';$('turnLabel').textContent='Turn '+S.turn;const n=S.cities.filter(c=>c.owner===0).length;$('cityCount').textContent=`${n} / ${S.cities.length} cities`;$('cityProgress').style.width=n/S.cities.length*100+'%';$('endTurn').disabled=S.current!==0;const card=$('selectionCard'),actions=$('actions');actions.innerHTML='';if(!sel){card.className='selection-card empty';card.innerHTML='<div class="selection-icon">⌖</div><div><h2>Select owned land</h2><p>Build mines, farms, and lumber camps to balance your economy.</p></div>';$('selectedCoords').textContent='Select a tile';return}const d=sel.data;$('selectedCoords').textContent=String.fromCharCode(65+d.x)+(d.y+1);card.className='selection-card';
 if(sel.kind==='unit'){const t=T[d.type],strong=t.strong.map(i=>T[i].name).join(', '),weak=t.weak.map(i=>T[i].name).join(', ');card.innerHTML=`<div class="selection-icon">${t.icon}</div><div><h2>${t.name} · Rank ${d.rank}</h2><p>${F[d.owner].name} · ${d.acted?'Orders used':'READY TO ACT'}</p><div class="health"><i style="width:${Math.max(0,d.hp/mh(d)*100)}%"></i></div><div class="unit-stats"><span><b>${d.hp}/${mh(d)}</b>HP</span><span><b>${atk(d)}</b>ATK</span><span><b>${def(d)}</b>DEF</span><span><b>${power(d)}</b>POWER</span></div><div class="matchup"><strong>Strong:</strong> ${strong}<br><b>Weak:</b> ${weak}<br>Move ${t.move} · Range ${t.range}</div></div>`;if(d.owner===0){const miss=mh(d)-d.hp,hc={gold:Math.max(2,Math.ceil(miss/3)),food:Math.max(2,Math.ceil(miss/2)),wood:0},rc={gold:7*d.rank,food:3*d.rank,wood:4*d.rank};button('✚ Heal to Full',miss?cost(hc):'Full health',()=>heal(d),!miss||d.acted,'heal-action');button('★ Rank Up',d.rank<3?cost(rc):'Elite rank',()=>rank(d),d.rank>=3||d.acted,'upgrade-action')}}
 else if(sel.kind==='city'){const fac=d.owner==null?null:F[d.owner];card.innerHTML=`<div class="selection-icon">♜</div><div><h2>${d.name} · Level ${d.level}</h2><p>${fac?fac.name:'Free city'}${d.capital?' · CAPITAL':''}</p><div class="unit-stats"><span><b>+${2+d.level}</b>Gold</span><span><b>+${1+d.level}</b>Food</span><span><b>${2+Math.floor((d.level-1)/2)}</b>Radius</span><span><b>${d.level}</b>Level</span></div></div>`;if(d.owner===0){Object.entries(T).forEach(([id,t])=>button(`${t.icon} ${t.name}`,cost(t.cost),()=>recruit(id,d),!!unit(d.x,d.y)||!afford(0,t.cost)));const cc={gold:12*d.level,food:7*d.level,wood:9*d.level};button('♜ Develop City',d.level<3?cost(cc):'Maximum level',()=>develop(d),d.level>=3,'primary-action action-wide');const a=S.upgrades[0].arms,z=S.upgrades[0].armor,ac={gold:14+a*10,food:0,wood:10+a*6},zc={gold:14+z*10,food:5+z*3,wood:10+z*6};button(`⚒ Armory +ATK (${a}/3)`,a<3?cost(ac):'Complete',()=>empire('arms',d),a>=3,'upgrade-action');button(`⛨ Armorworks +DEF (${z}/3)`,z<3?cost(zc):'Complete',()=>empire('armor',d),z>=3,'upgrade-action')}}
 else if(sel.kind==='resource'){const name=d.resource==='gold'?'Gold Mine':d.resource==='food'?'Farm':'Lumber Camp',ic={gold:6*d.resourceLevel,food:d.resource==='food'?2:0,wood:5*d.resourceLevel};card.innerHTML=`<div class="selection-icon">${d.resource==='gold'?'●':d.resource==='food'?'◆':'▲'}</div><div><h2>${name} · Level ${d.resourceLevel}</h2><p>${d.owner==null?'Unclaimed':F[d.owner].name} · Produces +${3*d.resourceLevel} ${d.resource} each turn.</p></div>`;if(d.owner===0){button('⬆ Improve Production',d.resourceLevel<3?cost(ic):'Maximum level',()=>improve(d),d.resourceLevel>=3,'upgrade-action action-wide');button('● Convert to Mine',cost({gold:6,food:4,wood:4}),()=>convertSite(d,'gold'),d.resource==='gold','site-gold');button('◆ Convert to Farm',cost({gold:6,food:4,wood:4}),()=>convertSite(d,'food'),d.resource==='food','site-food');button('▲ Convert to Lumber',cost({gold:6,food:4,wood:4}),()=>convertSite(d,'wood'),d.resource==='wood','site-wood');actions.insertAdjacentHTML?.('beforeend','<div class="economy-note">Converting resets the site to level 1. Use conversion when one resource is falling behind.</div>')}}
 else{const gc={gold:0,food:7,wood:9},fc={gold:8,food:0,wood:7},wc={gold:8,food:7,wood:0};card.innerHTML=`<div class="selection-icon">⌂</div><div><h2>Developable Land</h2><p>${d.terrain[0].toUpperCase()+d.terrain.slice(1)} inside Azure territory. Choose what your economy needs most.</p></div>`;button('● Build Gold Mine',cost(gc),()=>buildSite(d,'gold'),!afford(0,gc),'site-gold');button('◆ Build Farm',cost(fc),()=>buildSite(d,'food'),!afford(0,fc),'site-food');button('▲ Build Lumber Camp',cost(wc),()=>buildSite(d,'wood'),!afford(0,wc),'site-wood');actions.insertAdjacentHTML?.('beforeend','<div class="economy-note">Mine: +3 gold · Farm: +3 food · Lumber camp: +3 wood each turn.</div>')}}
function resize(){const r=C.parentElement.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);C.width=r.width*d;C.height=r.height*d;C.style.width=r.width+'px';C.style.height=r.height+'px';X.setTransform(d,0,0,d,0,0);tw=Math.min((r.width-30)/COLS,(r.height-30)/ROWS);th=tw;ox=(r.width-tw*COLS)/2;oy=(r.height-th*ROWS)/2;draw()}
function draw(){if(!S)return;X.clearRect(0,0,C.clientWidth,C.clientHeight);X.fillStyle='#102239';X.fillRect(0,0,C.clientWidth,C.clientHeight);S.map.forEach(drawTile);borders();moves.forEach(p=>outline(p,p.enemy?'#ff8075':'#ffe17a',false));targets.forEach(p=>outline(p,'#ff5d62',true));S.cities.forEach(drawCity);S.units.forEach(drawUnit)}
function outline(p,col,dash){X.strokeStyle=col;X.lineWidth=3;if(dash)X.setLineDash([4,3]);X.strokeRect(ox+p.x*tw+4,oy+p.y*th+4,tw-8,th-8);X.setLineDash([])}
function drawTile(t){const x=ox+t.x*tw,y=oy+t.y*th,col={water:'#2d6883',plains:'#78975d',forest:'#416f4d',hill:'#8a8060'};X.fillStyle=col[t.terrain];X.fillRect(x,y,tw+.5,th+.5);if(t.owner!=null){X.fillStyle=F[t.owner].color+'4d';X.fillRect(x+1,y+1,tw-2,th-2)}X.strokeStyle='#08151f55';X.lineWidth=1;X.strokeRect(x,y,tw,th);if(t.terrain==='forest'&&!t.resource){X.fillStyle='#1d4934';X.font=tw*.32+'px sans-serif';X.fillText('♣',x+tw*.36,y+th*.63)}if(t.terrain==='hill'&&!t.resource){X.fillStyle='#625a47';X.beginPath();X.moveTo(x+tw*.15,y+th*.73);X.lineTo(x+tw*.48,y+th*.27);X.lineTo(x+tw*.84,y+th*.73);X.fill()}if(t.resource){const sym=t.resource==='gold'?'●':t.resource==='food'?'◆':'▲';X.fillStyle='#07111ddd';X.fillRect(x+tw*.2,y+th*.2,tw*.6,th*.6);X.strokeStyle=t.resource==='gold'?'#ffd34f':t.resource==='food'?'#ff9875':'#a0df7d';X.lineWidth=2;X.strokeRect(x+tw*.2,y+th*.2,tw*.6,th*.6);X.fillStyle=X.strokeStyle;X.textAlign='center';X.textBaseline='middle';X.font=`bold ${Math.max(10,tw*.22)}px sans-serif`;X.fillText(sym,x+tw*.5,y+th*.42);X.font=`900 ${Math.max(7,tw*.12)}px sans-serif`;X.fillText('L'+t.resourceLevel,x+tw*.5,y+th*.65)}}
function borders(){S.map.forEach(t=>{if(t.owner==null)return;const x=ox+t.x*tw,y=oy+t.y*th;X.strokeStyle=F[t.owner].color;X.lineWidth=3;const line=(a,b,c,d)=>{X.beginPath();X.moveTo(a,b);X.lineTo(c,d);X.stroke()};if(tile(t.x,t.y-1)?.owner!==t.owner)line(x,y,x+tw,y);if(tile(t.x+1,t.y)?.owner!==t.owner)line(x+tw,y,x+tw,y+th);if(tile(t.x,t.y+1)?.owner!==t.owner)line(x,y+th,x+tw,y+th);if(tile(t.x-1,t.y)?.owner!==t.owner)line(x,y,x,y+th)})}
function drawCity(c){const x=ox+(c.x+.5)*tw,y=oy+(c.y+.52)*th,col=c.owner==null?'#f1e4c7':F[c.owner].color;X.save();X.translate(x,y);X.shadowColor='#000c';X.shadowBlur=6;X.fillStyle='#101c30';X.strokeStyle=col;X.lineWidth=c.capital?4:3;X.fillRect(-tw*.34,-th*.29,tw*.68,th*.48);X.strokeRect(-tw*.34,-th*.29,tw*.68,th*.48);X.shadowBlur=0;X.fillStyle=col;for(let i=-1;i<=1;i++)X.fillRect(i*tw*.22-tw*.07,-th*.4,tw*.14,th*.17);X.fillStyle='#07111e';X.fillRect(-tw*.08,0,tw*.16,th*.2);if(c.capital){X.fillStyle='#ffe078';X.font=`bold ${tw*.2}px sans-serif`;X.textAlign='center';X.fillText('◆',0,-th*.43)}X.font=`900 ${Math.max(7,tw*.14)}px sans-serif`;X.textAlign='center';X.textBaseline='middle';X.fillStyle='#08111e';X.fillRect(-tw*.38,th*.23,tw*.76,th*.18);X.fillStyle=col;X.fillText(`${c.owner==null?'FREE':F[c.owner].short} L${c.level}`,0,th*.32);X.restore()}
function drawUnit(u){const x=ox+(u.x+.5)*tw,y=oy+(u.y+.47)*th,t=T[u.type],ready=!u.acted;X.save();X.translate(x,y);if(ready){X.shadowColor='#ffe475';X.shadowBlur=11;X.strokeStyle='#ffe475';X.lineWidth=3;X.beginPath();X.arc(0,0,tw*.36,0,Math.PI*2);X.stroke()}if(sel?.kind==='unit'&&sel.data.id===u.id){X.strokeStyle='#fff';X.lineWidth=3;X.beginPath();X.arc(0,0,tw*.42,0,Math.PI*2);X.stroke()}X.shadowBlur=0;X.fillStyle=F[u.owner].dark;X.strokeStyle=F[u.owner].color;X.lineWidth=4;X.beginPath();X.arc(0,0,tw*.29,0,Math.PI*2);X.fill();X.stroke();X.textAlign='center';X.textBaseline='middle';X.fillStyle='#fff';X.font=tw*.25+'px sans-serif';X.fillText(t.icon,0,-th*.04);X.font=`900 ${Math.max(7,tw*.12)}px sans-serif`;X.fillText(t.mark,0,th*.16);X.fillStyle='#07111e';X.fillRect(-tw*.33,th*.31,tw*.66,th*.17);X.fillStyle=u.hp/mh(u)>.45?'#77df82':'#ff725f';X.fillRect(-tw*.31,th*.33,tw*.62*Math.max(0,u.hp/mh(u)),th*.05);X.fillStyle='#fff';X.fillText(`P${power(u)} R${u.rank}`,0,th*.43);if(ready){X.fillStyle='#ffe475';X.beginPath();X.arc(tw*.3,-th*.27,Math.max(3,tw*.07),0,Math.PI*2);X.fill()}X.restore()}
function point(e){const r=C.getBoundingClientRect(),p=e.touches?.[0]||e;return{x:Math.floor((p.clientX-r.left-ox)/tw),y:Math.floor((p.clientY-r.top-oy)/th)}}
function toast(m){clearTimeout(timer);$('toast').textContent=m;$('toast').classList.add('show');timer=setTimeout(()=>$('toast').classList.remove('show'),2400)}
function begin(load=false){if(load){try{S=migrate(JSON.parse(localStorage.getItem(SAVE)))}catch{S=fresh()}}else S=fresh($('difficulty').value);sel=null;moves=[];targets=[];$('startOverlay').classList.remove('open');save();ui();resize();toast('Gold rings mark units that are ready to act.')}
C.addEventListener('click',e=>{const p=point(e);if(tile(p.x,p.y))select(p.x,p.y)});window.addEventListener('resize',resize);$('endTurn').onclick=end;$('newGame').onclick=()=>begin(false);$('continueGame').onclick=()=>begin(true);$('helpBtn').onclick=()=>$('helpOverlay').classList.add('open');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).classList.remove('open'));$('playAgain').onclick=()=>{$('resultOverlay').classList.remove('open');S=fresh($('difficulty').value);sel=null;moves=[];targets=[];save();ui();resize()};document.addEventListener('keydown',e=>{if(e.key==='Enter'&&S?.current===0&&!document.querySelector('.overlay.open'))end();if(e.key==='Escape')document.querySelectorAll('.overlay.open:not(#startOverlay)').forEach(x=>x.classList.remove('open'))});if(localStorage.getItem(SAVE))$('continueGame').classList.remove('hidden');
})();
